# Your email config here
sender_email: "<YOUR_EMAIL_HERE>"
receiver_email: "<YOUR_SENDER_EMAIL_HERE>"
sender_email_password: "<YOUR_PASSWORD_HERE>"
send_email: False

# CSV and Images Saving paths
csv_path: "./csv_downloads"
image_path: "./image_downloads"

# Queries
search_queries:
  - Cantharellaceae,Cantharellus formosus mushroom
  - Cantharellaceae,Cantharellus subalbidus mushroom
  - Cantharellaceae,Cantharellus cibarius mushroom
  - Morchellaceae,Morchella esculenta mushroom
  - Morchellaceae,Morchella elata mushroom
  - Morchellaceae,Morchella importuna mushroom
  - Boletaceae,Boletus edulis mushroom
  - Tricholomataceae,Tricholoma magnivelare mushroom
  - Pleurotaceae,Pleurotus ostreatus mushroom
  - Coprinaceae,Coprinus comatus mushroom
  - Hypocreaceae,Hypomyces lactifluorum mushroom
  - Polyporaceae,Laetiporus sulphureus mushroom
  - Polyporaceae,Trametes versicolor mushroom
  - Hydnaceae,Hydnum repandum mushroom
  - Hydnaceae,Hydnum umbilicatum mushroom
  - Lycoperdaceae,Calvatia spp. mushroom
  - Lycoperdaceae,Lycoperdon spp. mushroom
  - Suillaceae,Suillus luteus mushroom
  - Sparassidaceae,Sparassis crispa mushroom
  - Clavariaceae,Ramaria spp. mushroom
  - Tuberaceae,Tuber spp. mushroom
  - Tricholomataceae,Clitocybe nuda mushroom
  - Tremellaceae,Tremella mesenterica mushroom
  - Hydnaceae,Hydnum repandum mushroom
  - Boletaceae,Boletus zelleri mushroom
  - Boletaceae,Boletus mirabilis mushroom
  - Amanitaceae,Amanita muscaria (Fly Agaric, noted for its toxicity) mushroom
  - Amanitaceae,Amanita pantherina (Panther Cap, also toxic) mushroom
  - Gomphidiaceae,Chroogomphus tomentosus (Woolly Pine Spike) mushroom
  - Russulaceae,Lactarius deliciosus (Saffron Milk Cap) mushroom
  - Russulaceae,Russula xerampelina (Shrimp Russula) mushroom
  - Strophariaceae,Stropharia ambigua (Questionable Stropharia) mushroom
  - Gomphidiaceae,Gomphidius glutinosus (Slippery Jack's Relative) mushroom
  - Hericiaceae,Hericeum erinaceus (Lion's Mane Mushroom) mushroom
  - Psathyrellaceae,Coprinellus micaceus (Mica Cap) mushroom
  - Entolomataceae,Entoloma abortivum (Aborted Entoloma) mushroom
  - Auriscalpiaceae,Auriscalpium vulgare (Pinecone Mushroom) mushroom
  - Marasmiaceae,Marasmius oreades (Fairy Ring Mushroom) mushroom
  - Phallaceae,Mutinus caninus (Dog Stinkhorn) mushroom
  - Bondarzewiaceae,Hericium abietis (Coral Tooth) mushroom
  - Marasmiaceae,Armillaria mellea (Honey Mushroom) mushroom
  - Cortinariaceae,Cortinarius caperatus (The Gypsy) mushroom
  - Pleurotaceae,Hohenbuehelia mastrucata (Woolly Oyster) mushroom
  - Pholiota nameko (Nameko) mushroom
  - Paxillaceae,Paxillus involutus (Brown Roll-Rim) mushroom
  - Tapinellaceae,Tapinella atrotomentosa (Velvet Rollrim) mushroom
  - Fomitopsidaceae,Fomitopsis cajanderi (Rosy Conk) mushroom
  - Inocybaceae,Inocybe geophylla (Fibrecap) mushroom
  - Strophariaceae,Hypholoma fasciculare (Sulphur Tuft) mushroom
  - Gomphidiaceae,Gomphidius subroseus (Rosy Spike) mushroom
  - Ganodermataceae,Ganoderma lucidum mushroom
  - Pleurotaceae,Pleurotus eryngii mushroom
  - Pleurotaceae,Pleurotus citrinopileatus mushroom
  - Pleurotaceae,Pleurotus pulmonarius mushroom
  - Polyporaceae,Trametes trogii mushroom
  - Meripilaceae,Meripilus giganteus mushroom
  - Fomitopsidaceae,Fomitopsis pinicola mushroom
  - Strophariaceae,Pholiota squarrosoides mushroom
  - Strophariaceae,Pholiota aurivella mushroom
  - Marasmiaceae,Crinipellis zonata mushroom
  - Amanitaceae,Amanita phalloides mushroom
  - Amanitaceae,Amanita ocreata mushroom
  - Amanitaceae,Amanita virosa mushroom
  - Russulaceae,Russula emetica mushroom
  - Russulaceae,Russula virescens mushroom
  - Russulaceae,Russula brevipes mushroom
  - Strophariaceae,Stropharia rugosoannulata mushroom
  - Gomphidiaceae,Gomphidius smithii mushroom
  - Suillaceae,Suillus granulatus mushroom
  - Suillaceae,Suillus brevipes mushroom
  - Lycoperdaceae,Lycoperdon perlatum mushroom
  - Lycoperdaceae,Lycoperdon pyriforme mushroom
  - Boletaceae,Boletus chrysenteron mushroom
  - Boletaceae,Boletus subtomentosus mushroom
  - Boletaceae,Leccinum aurantiacum mushroom
  - Hericium coralloides mushroom
  - Polyporaceae,Ganoderma applanatum mushroom
  - Polyporaceae,Ganoderma oregonense mushroom
  - Pleurotaceae,Pleurotus djamor mushroom
  - Polyporaceae,Trametes versicolor mushroom
  - Polyporaceae,Trametes hirsuta mushroom
  - Polyporaceae,Trametes pubescens mushroom
  - Strophariaceae,Hypholoma lateritium mushroom
  - Strophariaceae,Hypholoma capnoides mushroom
  - Amanitaceae,Amanita gemmata mushroom
  - Amanitaceae,Amanita aprica mushroom
  - Paxillaceae,Paxillus panuoides mushroom
  - Paxillaceae,Paxillus vernalis mushroom
  - Auriscalpiaceae,Lentinellus ursinus mushroom
  - Gomphidiaceae,Chroogomphus rutilus mushroom
  - Fomitopsidaceae,Fomitopsis mounceae mushroom
  - Fomitopsidaceae,Fomitopsis officinalis mushroom
  - Hypocreaceae,Claviceps purpurea mushroom
  - Physalacriaceae,Armillaria tabescens mushroom
  - Physalacriaceae,Armillaria gallica mushroom
  - Agaricaceae,Agaricus bisporus mushroom
  - Agaricaceae,Agaricus brunnescens mushroom
  - Agaricaceae,Agaricus campestris mushroom
  - Hydnangiaceae,Laccaria bicolor mushroom
  - Hydnangiaceae,Laccaria laccata mushroom
  - Agaricaceae,Agaricus arvensis mushroom
  - Agaricaceae,Agaricus augustus mushroom
  - Omphalotaceae,Gymnopus dryophilus mushroom
  - Strophariaceae,Kuehneromyces mutabilis mushroom
  - Pluteaceae,Pluteus cervinus mushroom
  - Agaricaceae,Macrolepiota procera mushroom
  - Lepiotaceae,Leucoagaricus leucothites mushroom
  - Psathyrellaceae,Parasola plicatilis mushroom
  - Psathyrellaceae,Psathyrella candolleana mushroom
  - Amanitaceae,Amanita rubescens mushroom
  - Amanitaceae,Amanita fulva mushroom
  - Amanitaceae,Amanita velosa mushroom
  - Hygrophoraceae,Hygrocybe conica mushroom
  - Hygrophoraceae,Hygrocybe coccinea mushroom
  - Hygrophoraceae,Hygrocybe psittacina mushroom
  - Tricholomataceae,Lepista nuda mushroom
  - Tricholomataceae,Lepista sordida mushroom
  - Cortinariaceae,Cortinarius traganus mushroom
  - Cortinariaceae,Cortinarius violaceus mushroom
  - Mythicomycetaceae,Calocera viscosa mushroom
  - Pleurotaceae,Pleurotus tuber-regium mushroom
  - Pleurotaceae,Pleurotus nebrodensis mushroom
  - Pluteaceae,Volvariella volvacea mushroom
  - Ramariaceae,Ramaria formosa mushroom
  - Bolbitiaceae,Conocybe filaris mushroom
  - Bolbitiaceae,Conocybe apala mushroom
  - Tricholomataceae,Tricholoma terreum mushroom
  - Tricholomataceae,Tricholoma scalpturatum mushroom
  - Russulaceae,Lactarius uvidus mushroom
  - Russulaceae,Lactarius camphoratus mushroom
  - Entolomataceae,Clitopilus prunulus mushroom
  - Entolomataceae,Entoloma sinuatum mushroom
  - Ganodermataceae,Ganoderma tsugae mushroom
  - Ganodermataceae,Ganoderma curtisii mushroom
  - Hymenogastraceae,Panaeolus cinctulus mushroom
  - Hymenogastraceae,Galerina marginata mushroom
  - Inocybaceae,Inocybe lacera mushroom
  - Inocybaceae,Inocybe fastigiata mushroom
  - Marasmiaceae,Marasmius rotula mushroom
  - Marasmiaceae,Marasmius haematocephalus mushroom
  - Paxillaceae,Paxillus ammoniavirescens mushroom
  - Polyporaceae,Laetiporus conifericola mushroom
  - Polyporaceae,Polyporus squamosus mushroom
  - Strophariaceae,Stropharia coronilla mushroom
  - Strophariaceae,Stropharia aeruginosa mushroom
  - Suillaceae,Suillus bellinii mushroom
  - Suillaceae,Suillus variegatus mushroom
  - Tremellaceae,Dacrymyces chrysospermus mushroom
  - Tremellaceae,Tremella fuciformis mushroom
  - Xylariaceae,Xylaria polymorpha mushroom

# Max Image Limit
images_limit: 200
